In [1]:
import numpy as np
import tensorflow as tf

In [ ]:
with tf.Session() as sess:
    ipt = tf.placeholder(tf.float32, shape=(None, 2, 3))
    w = tf.get_variable('wx_name', shape=[3, 1], dtype=tf.float32)
    out = tf.matmul(ipt, w)

    sess.run(tf.global_variables_initializer())
    
    output = sess.run(out, {ipt: np.random.rand(10, 2, 3)})
    print(output) 

In [6]:
import tensorflow as tf
 
#our NN's output
logits=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])
#step1:do softmax
y=tf.nn.softmax(logits)
#true label
y_=tf.constant([[0.0,1.0,0.0],[0.0,0.0,1.0],[0.0,0.0,1.0]])
#step2:do cross_entropy
cross_entropy = -tf.reduce_sum(y_*tf.log(y), axis=1)
#do cross_entropy just one step
cross_entropy2=tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_)#dont forget tf.reduce_sum()!!
 
with tf.Session() as sess:
    softmax=sess.run(y)
    c_e = sess.run(cross_entropy)
    c_e2 = sess.run(cross_entropy2)
    print("step1:softmax result=")
    print(softmax)
    print("step2:cross_entropy result=")
    print(c_e)
    print("Function(softmax_cross_entropy_with_logits) result=")
    print(c_e2)

step1:softmax result=
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]
step2:cross_entropy result=
[1.4076059  0.407606   0.40760598]
Function(softmax_cross_entropy_with_logits) result=
[1.4076059  0.40760595 0.40760595]
